# Generated by Django 4.1.1 on 2022-09-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
