# Generated by Django 4.1.1 on 2022-09-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_alter_port_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
