# Generated by Django 4.1.1 on 2022-10-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_alter_port_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imo', models.IntegerField(unique=True)),
                ('trip_date', models.DateField()),
                ('submit_date', models.DateField(auto_now=True)),
                ('dest_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='ports.port')),
                ('origin_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='ports.port')),
            ],
        ),
    ]
